myfirst/myfirst/apps/articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('test/', views.test, name='test'),
]

myfirst/myfirst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

myfirst/myfirst/apps/articles/models.py
from django.db import models
from django.utils import timezone
import datetime


class Article(models.Model):
    article_title = models.CharField('article title', max_length=200)
    article_text = models.TextField('article text')
    pub_date = models.DateTimeField('date of publication')

# THIS MUST BE IN EVERY MODEL!!!
    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'ARTICLE'
        verbose_name_plural = 'ARTICLES'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('author', max_length=50)
    comment_text = models.CharField('comment text', max_length=200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'COMMENT'
        verbose_name_plural = 'COMMENTS'

myfirst/myfirst/apps/articles/views.py
from django.shortcuts import render
from .models import Article, Comment
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse


def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def test(request):
    return HttpResponse("Testing is perfect!")


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('Article not found')

    latest_comments_list = a.comment_set.order_by('-id')[:10]
    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})


def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('Article not found')
    a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])
    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))

myfirst/myfirst/templates/articles/detail.html
{% extends 'base.html' %}

<title>{% block title %}{{article.article_title}}{% endblock %}</title>

{% block content %}

<h2>{{article.article_title}}</h2>

<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>

{% if article.was_published_recently %}
NEW ARTICLE!!!
{% endif %}

<hr>

{% if latest_comments_list %}
    {% for c in latest_comments_list %}
        <a>
            <strong>{{c.author_name}}</strong>
            <p>{{c.comment_text}}</p>
        </a>
    {% endfor %}

{% else %}
Comments not found! Become first to comment!
{% endif %}

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Your name" name="name"><br>
    <textarea name="text" required="" placeholder="Comment text" cols="30" rows="10"></textarea><br>
    <button type="submit">Leave your comment</button>

 </form>

{% endblock %}

myfirst/myfirst/templates/articles/list.html
{% extends 'base.html' %}

<title>{% block title %}Last articles{% endblock %}</title>

{% block content %}

    {% if latest_articles_list %}

        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id%}">{{a.article_title}}</a>
        {% endfor %}

    {% else %}
        Articles not found
    {% endif %}

{% endblock %}

myfirst/myfirst/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MY SITE{% endblock %}</title>
</head>
<body>

    {% block content %}{% endblock %}

</body>
</html>